### ISSUE TITLE
use unsubscribe method of Subscriptions

### ISSUE THREAD

**Issue by chrisguttandin** [spectjs/sube#1]
I think there is a bug in line 19.

https://github.com/spectjs/sube/blob/2fbeffe49616aff3043c83a427e4468fe63ce87e/sube.js#L19

It should probably be `target[Symbol.observable]?.().subscribe?.( next, error, complete ).unsubscribe` instead since an `Observable` returns a subscription when calling `subscribe()` which has a `unsubscribe()` method.

As always it's of course totally possible that I'm missing something.

**Comment by dy** [comment]
Good point, thanks! Fixed in v2.2.0.

**Comment by chrisguttandin** [comment]
Thanks a lot.
